use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();
    let kernel_dir = PathBuf::from(&manifest_dir).join("../../target/kernels");

    let kernels = [
        "byte_classifier",
        "json_scanner",
        "command_router",
        "leak_scanner",
        "sanitizer",
        "fused_safety",
        "search",
    ];

    // Generate embedded_kernels.rs with include_bytes! for each .so
    let mut code = String::from("// Auto-generated by build.rs — do not edit\n");
    for name in &kernels {
        let so_path = kernel_dir.join(format!("lib{name}.so"));
        let abs = so_path.canonicalize().unwrap_or_else(|_| {
            eprintln!("Warning: kernel not found at {so_path:?}. Run ./build.sh first.");
            so_path
        });
        let upper = name.to_uppercase();
        code.push_str(&format!(
            "pub const {upper}: &[u8] = include_bytes!(\"{}\");\n",
            abs.display()
        ));
    }
    // Version tag for cache invalidation
    let version = env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.0.0".into());
    code.push_str(&format!("pub const VERSION: &str = \"{version}\";\n"));

    fs::write(PathBuf::from(&out_dir).join("embedded_kernels.rs"), &code).unwrap();

    println!("cargo:rerun-if-changed=../../target/kernels");

    // --- Local LLM: link pre-built llama.cpp + eakv (only with local-llm feature) ---
    #[cfg(feature = "local-llm")]
    {
        link_llama_cpp();
        link_eakv();
    }
}

#[cfg(feature = "local-llm")]
fn link_llama_cpp() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let llama_build = std::path::PathBuf::from(&manifest_dir)
        .join("../../vendor/llama.cpp/build");

    // Link llama.cpp static libraries (built via cmake)
    println!("cargo:rustc-link-search=native={}", llama_build.join("src").display());
    println!("cargo:rustc-link-search=native={}", llama_build.join("ggml/src").display());
    println!("cargo:rustc-link-search=native={}", llama_build.join("ggml/src/ggml-cpu").display());

    println!("cargo:rustc-link-lib=static=llama");
    println!("cargo:rustc-link-lib=static=ggml");
    println!("cargo:rustc-link-lib=static=ggml-base");
    println!("cargo:rustc-link-lib=static=ggml-cpu");

    // System libs needed by llama.cpp
    println!("cargo:rustc-link-lib=stdc++");
    println!("cargo:rustc-link-lib=m");
    println!("cargo:rustc-link-lib=pthread");
}

#[cfg(feature = "local-llm")]
fn link_eakv() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    // eakv is a sibling directory: /root/dev/eakv
    let eakv_build = std::path::PathBuf::from(&manifest_dir)
        .join("../../../eakv/build");
    let eakv_abs = eakv_build.canonicalize().unwrap_or(eakv_build);
    println!("cargo:rustc-link-search=native={}", eakv_abs.display());
    println!("cargo:rustc-link-lib=static=eakv");
}
