use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();
    let kernel_dir = PathBuf::from(&manifest_dir).join("../../target/kernels");

    let kernels = [
        "byte_classifier",
        "json_scanner",
        "command_router",
        "leak_scanner",
        "sanitizer",
        "fused_safety",
        "search",
    ];

    // Generate embedded_kernels.rs with include_bytes! for each .so
    let mut code = String::from("// Auto-generated by build.rs — do not edit\n");
    for name in &kernels {
        let so_path = kernel_dir.join(format!("lib{name}.so"));
        let abs = so_path.canonicalize().unwrap_or_else(|_| {
            eprintln!("Warning: kernel not found at {so_path:?}. Run ./build.sh first.");
            so_path
        });
        let upper = name.to_uppercase();
        code.push_str(&format!(
            "pub const {upper}: &[u8] = include_bytes!(\"{}\");\n",
            abs.display()
        ));
    }
    // Version tag for cache invalidation
    let version = env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.0.0".into());
    code.push_str(&format!("pub const VERSION: &str = \"{version}\";\n"));

    fs::write(PathBuf::from(&out_dir).join("embedded_kernels.rs"), &code).unwrap();

    println!("cargo:rerun-if-changed=../../target/kernels");
}
