use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();
    let repo_root = PathBuf::from(&manifest_dir).join("../..");

    // --- Eä SIMD kernels (pre-built .so files checked into the repo) ---
    // Use pre-built kernels from kernels/prebuilt/ (no Eä compiler needed).
    // To rebuild from .ea sources: ./build.sh
    let kernel_dir = {
        let prebuilt = repo_root.join("kernels/prebuilt");
        let target = repo_root.join("target/kernels");
        if prebuilt.join("libfused_safety.so").exists() {
            prebuilt
        } else if target.join("libfused_safety.so").exists() {
            target
        } else {
            panic!(
                "No pre-built kernels found. Either:\n\
                 - Check that kernels/prebuilt/*.so exist, or\n\
                 - Run ./build.sh to compile from .ea sources"
            );
        }
    };

    let kernels = [
        "byte_classifier",
        "json_scanner",
        "command_router",
        "leak_scanner",
        "sanitizer",
        "fused_safety",
        "search",
        "search_avx512",
    ];

    let mut code = String::from("// Auto-generated by build.rs — do not edit\n");
    for name in &kernels {
        let so_path = kernel_dir.join(format!("lib{name}.so"));
        let abs = so_path.canonicalize().unwrap_or_else(|_| {
            panic!("Kernel not found: {so_path:?}");
        });
        let upper = name.to_uppercase();
        code.push_str(&format!(
            "pub const {upper}: &[u8] = include_bytes!(\"{}\");\n",
            abs.display()
        ));
    }
    let version = env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.0.0".into());
    code.push_str(&format!("pub const VERSION: &str = \"{version}\";\n"));

    fs::write(PathBuf::from(&out_dir).join("embedded_kernels.rs"), &code).unwrap();

    println!("cargo:rerun-if-changed=../../kernels/prebuilt");
    println!("cargo:rerun-if-changed=../../target/kernels");

    // --- Local LLM: build llama.cpp + eakv from source ---
    #[cfg(feature = "local-llm")]
    {
        let repo_root = repo_root.canonicalize().unwrap();
        build_llama_cpp(&repo_root, &manifest_dir);
        build_eakv(&repo_root, &manifest_dir);
    }
}

#[cfg(feature = "local-llm")]
fn ensure_submodule(repo_root: &std::path::Path, path: &str) {
    let dir = repo_root.join(path);
    // Check if the submodule directory has content (not just an empty dir)
    if !dir.join(".git").exists() && !dir.join("CMakeLists.txt").exists()
       && !dir.join("Makefile").exists() && !dir.join("include").exists()
    {
        eprintln!("Initializing submodule: {path}");
        let status = std::process::Command::new("git")
            .args(["submodule", "update", "--init", "--depth", "1", path])
            .current_dir(repo_root)
            .status()
            .expect("failed to run git");
        if !status.success() {
            panic!(
                "Failed to initialize submodule '{path}'.\n\
                 Run: git submodule update --init --recursive"
            );
        }
    }
}

#[cfg(feature = "local-llm")]
fn build_llama_cpp(repo_root: &std::path::Path, manifest_dir: &str) {
    ensure_submodule(repo_root, "third_party/llama.cpp");

    let llama_src = repo_root.join("third_party/llama.cpp");
    let llama_include = llama_src.join("include");
    let ggml_include = llama_src.join("ggml/include");

    // Build llama.cpp via cmake (CPU-only, static libs, always optimized)
    let dst = cmake::Config::new(&llama_src)
        .define("LLAMA_BUILD_TESTS", "OFF")
        .define("LLAMA_BUILD_EXAMPLES", "OFF")
        .define("LLAMA_BUILD_SERVER", "OFF")
        .define("BUILD_SHARED_LIBS", "OFF")
        .define("GGML_CUDA", "OFF")
        .define("GGML_METAL", "OFF")
        .define("GGML_VULKAN", "OFF")
        .define("GGML_OPENMP", "ON")
        .define("CMAKE_BUILD_TYPE", "Release")
        .build();

    // Compile our C++ generation loop shim
    cc::Build::new()
        .cpp(true)
        .file(format!("{manifest_dir}/csrc/eaclaw_generate.cpp"))
        .include(&llama_include)
        .include(&ggml_include)
        .flag("-std=c++17")
        .flag("-O2")
        .compile("eaclaw_generate");

    // Link llama.cpp static libraries
    println!("cargo:rustc-link-search=native={}", dst.join("lib").display());
    // Some cmake builds put libs in lib64
    println!("cargo:rustc-link-search=native={}", dst.join("lib64").display());

    println!("cargo:rustc-link-lib=static=llama");
    println!("cargo:rustc-link-lib=static=ggml");
    println!("cargo:rustc-link-lib=static=ggml-base");
    println!("cargo:rustc-link-lib=static=ggml-cpu");

    // System libs needed by llama.cpp
    println!("cargo:rustc-link-lib=stdc++");
    println!("cargo:rustc-link-lib=m");
    println!("cargo:rustc-link-lib=pthread");
    println!("cargo:rustc-link-lib=gomp");

    println!("cargo:rerun-if-changed=csrc/eaclaw_generate.cpp");
    println!("cargo:rerun-if-changed=../../third_party/llama.cpp/include");
}

#[cfg(feature = "local-llm")]
fn build_eakv(repo_root: &std::path::Path, manifest_dir: &str) {
    ensure_submodule(repo_root, "third_party/eakv");

    let eakv_src = repo_root.join("third_party/eakv/src");
    let eakv_include = repo_root.join("third_party/eakv/include");
    let eakv_kernels = repo_root.join("third_party/eakv-kernels");

    // Build eakv C sources (excluding cli.c which has main())
    let c_files: Vec<_> = ["cache.c", "attention.c", "io.c", "ggml_type.c", "llama_bridge.c"]
        .iter()
        .map(|f| eakv_src.join(f))
        .collect();

    let ggml_include = repo_root.join("third_party/llama.cpp/ggml/include");

    let mut build = cc::Build::new();
    build
        .include(&eakv_include)
        .include(&eakv_src)
        .include(&ggml_include)
        .flag("-std=c11")
        .flag("-O2");

    for f in &c_files {
        build.file(f);
    }
    build.compile("eakv_c");

    // Link pre-built Eä kernel objects
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let kernel_dir = PathBuf::from(&out_dir).join("eakv_kernels");
    fs::create_dir_all(&kernel_dir).unwrap();

    // Copy .o files to OUT_DIR and create a static archive
    let mut ar_cmd = std::process::Command::new("ar");
    ar_cmd.arg("rcs");
    ar_cmd.arg(kernel_dir.join("libeakv_kernels.a"));

    for entry in fs::read_dir(&eakv_kernels).expect("third_party/eakv-kernels/ not found") {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().map_or(false, |e| e == "o") {
            let dest = kernel_dir.join(path.file_name().unwrap());
            fs::copy(&path, &dest).unwrap();
            ar_cmd.arg(&dest);
        }
    }

    let ar_status = ar_cmd.status().expect("failed to run ar");
    if !ar_status.success() {
        panic!("Failed to create eakv kernel archive");
    }

    println!("cargo:rustc-link-search=native={}", kernel_dir.display());
    println!("cargo:rustc-link-lib=static=eakv_kernels");
    let _ = manifest_dir; // used by caller

    println!("cargo:rerun-if-changed=../../third_party/eakv/src");
    println!("cargo:rerun-if-changed=../../third_party/eakv-kernels");
}
